### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by ronbak**
Hi,

this merge request fixes some minor issues.
It was created with help of [Feram](https://github.com/feramhq/feram).

If it helped to improve this repository,
please consider to [star Feram's repo](https://github.com/feramhq/feram) to show some love! 😊

PS:
The [Feram team](https://github.com/feramhq) is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co](http://feram.co).

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@ronbak, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by artwyman** [comment]
This seems to be an automated PR which just spell-checks a typo in a comment.  Not high value, and no CLA, so I'm going to close it out.

@ronbak I'm willing to merge if you sign the CLA.  Feram sounds like a cool idea, so I wish you luck, but apparently it's not finding anything really interesting in this repo yet.

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@ronbak, thanks for signing the CLA!

**Comment by ronbak** [comment]
I signed the CLA. Why does everything have to be so complicated =D
Thanks for the good luck. We'll need it … YC interview on Monday =P

**Comment by artwyman** [comment]
Yeah, the CLA is a necessary evil.  Since this library is used in commercial apps at Dropbox, we want to be really careful that nobody submits code without giving us the appropriate rights to use it.

**Pull request merged**
